feat: implement transfer admin and upgrade sotw features
blubbofi/blubbo-contracts pull request #57
Opened 2024-10-27 12:35 UTC by Juyeong-Byeon

## what
I implemented sotw::handlers::admin::handle_upgrade_code and sotw::handlers::admin::handle_transfer_admin to enable the upgrade of SOTW and the transfer of admin privileges.

To implement the transfer admin feature, I defined the schema for SOTW storage as follows:
```tlb
storage$_
  toncoin_balance:uint256
  owner_address:MsgAddressInt
  admin_address:MsgAddressInt
   = SingleOwnerTonWalletStorage
```

toncoin_balance and owner_address already existed, but they were not documented in the TLB.

2024-12-20 02:07 UTC, 9oelM commented on contracts/single_owner_ton_wallet/single_owner_ton_wallet.fc
> +    return ();
```suggestion
```

2024-12-20 02:07 UTC, 9oelM commented on contracts/single_owner_ton_wallet/single_owner_ton_wallet.fc
> +    return ();
```suggestion
```

2024-12-20 02:07 UTC, 9oelM commented on contracts/single_owner_ton_wallet/sotw_reserves.fc
> +
avoid making unnecessary changes

2024-12-20 02:10 UTC, 9oelM commented on contracts/single_owner_ton_wallet/single_owner_ton_wallet.fc
> +  } elseif (op == op::transfer_admin) {
define the op in sotw_constants.fc

2024-12-20 07:04 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/single_owner_ton_wallet.fc
> +    return ();
0431cf3fdcc17dba59d749339013c3fbf56c5e50

2024-12-20 07:04 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/single_owner_ton_wallet.fc
> +    return ();
0431cf3fdcc17dba59d749339013c3fbf56c5e50

2024-12-20 07:04 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/sotw_reserves.fc
> +
0431cf3fdcc17dba59d749339013c3fbf56c5e50

2024-12-20 07:38 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/single_owner_ton_wallet.fc
> +  } elseif (op == op::transfer_admin) {
f6ba01e28aa2d2fc3b704f32ce32f9f7b2c9a27c

2024-12-21 15:30 UTC, 9oelM commented
Deployment script is meant to be like database migration code: once it is written, it stays unchanged forever.

When you update the contract code and need to deploy again, you need to write a new deployment script afresh instead of committing changes to the existing deployment script.

This way we can know how the contracts were deployed or updated each time in the past

2024-12-22 05:50 UTC, Juyeong-Byeon commented
@9oelM thanks I reverted changes about deploy script 8998aaa19d74f164b5172d36df34df4859cbc4cc

2024-12-23 14:21 UTC, 9oelM requested changes

2024-12-23 14:21 UTC, 9oelM commented on contracts/single_owner_ton_wallet/sotw_reserves.fc
> +}
Avoid unnecessary changes

2024-12-23 14:21 UTC, 9oelM commented on contracts/utils.fc
> +}
Same

2024-12-23 14:21 UTC, 9oelM commented on tests/SingleOwnerTonWallet.spec.ts
> +    it(`can transfer admin`, async () => {
Need to add a test on:
Non-admin cannot transfer admin
Non-admin cannot upgrade code

Such test cases are missing in Blubbo master contract tests too, but i just didnt have time to add these. But we need them anyway

2024-12-23 14:25 UTC, 9oelM commented on contracts/single_owner_ton_wallet/handlers/admin/handle_transfer_admin.fc
> +
avoid making too many newlines. 
SLOC is the primary measure of audit costs. So we will want to reduce unnecessary newlines.

2024-12-23 14:25 UTC, 9oelM commented on contracts/single_owner_ton_wallet/handlers/admin/handle_transfer_admin.fc
> +
same here

2024-12-23 14:25 UTC, 9oelM commented on contracts/single_owner_ton_wallet/handlers/admin/handle_transfer_admin.fc
> +
same here

2024-12-23 14:26 UTC, 9oelM commented on contracts/single_owner_ton_wallet/helpers/handler_helpers.fc
> +-}
these comments are written in the other handler_helpers file, so let's not duplicate it here

2024-12-23 14:29 UTC, 9oelM commented on contracts/single_owner_ton_wallet/single_owner_ton_wallet.fc
> +}
i dont think this is necessary because it's too easy to get admin address from fetch_storage.

2024-12-23 14:30 UTC, 9oelM commented on contracts/single_owner_ton_wallet/sotw_message_sender.fc
> +() message_sender::refund_excess(
need to write a warning above this function, talking about the danger of not dealing with msg_mode::CARRY_ALL_BALANCE properly as it might send all TON that the contract owns if there's no appropriate call to raw_reserve before

2024-12-23 14:30 UTC, 9oelM commented on package-lock.json
> +            "resolved": "https://registry.npmjs.org/@ton/core/-/core-0.59.1.tgz",
please rebase as I have updated the package

2024-12-23 14:31 UTC, 9oelM commented on tests/SingleOwnerTonWallet.spec.ts
>          const approxOtherFeesLowerBound = toNano('0.0008');
I think if the upper bound increased, the lower bound needs to increase too?

2024-12-23 14:32 UTC, 9oelM commented on tests/SingleOwnerTonWallet.spec.ts
> +            success: true,
include opcode too

2024-12-23 14:32 UTC, 9oelM commented on tests/SingleOwnerTonWallet.spec.ts
> +            success: true,
include opcode too

2024-12-23 14:32 UTC, 9oelM commented on tests/SingleOwnerTonWallet.spec.ts
> +            success: false,
include opcode too

2024-12-23 14:33 UTC, 9oelM commented on tests/SingleOwnerTonWallet.spec.ts
> +        });
this needs to be another test case

2024-12-23 14:34 UTC, 9oelM commented on contracts/single_owner_ton_wallet/handlers/admin/handle_upgrade_code.fc
> +
spaces

2024-12-26 04:39 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/sotw_reserves.fc
> +}
This change was created because I removed 
unnecessary line bellow.

2024-12-26 04:39 UTC, Juyeong-Byeon commented on contracts/utils.fc
> +}
This change was created because I removed 
unnecessary line bellow.

2024-12-26 04:44 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/handlers/admin/handle_upgrade_code.fc
> +
[e7c03fe11f5a8504d4e4d625c314bc69b62f7620](https://github.com/blubbofi/blubbo-contracts/commit/e7c03fe11f5a8504d4e4d625c314bc69b62f7620#diff-006da614e98d3640723944a9cf748c72320464e69620f7b3545ba847ffe8222aL31-L32) removed

2024-12-26 04:45 UTC, Juyeong-Byeon commented on package-lock.json
> +            "resolved": "https://registry.npmjs.org/@ton/core/-/core-0.59.1.tgz",
I rebased this branch!

2024-12-26 04:46 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/helpers/handler_helpers.fc
> +-}
[ removed!](https://github.com/blubbofi/blubbo-contracts/commit/e7c03fe11f5a8504d4e4d625c314bc69b62f7620#diff-d5f9b6dab68b81a34ef91d05452ffa9d221c15605aa72ab6f326f6de093f77d8L5-L21)

2024-12-26 04:47 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/handlers/admin/handle_transfer_admin.fc
> +
[removed](https://github.com/blubbofi/blubbo-contracts/commit/e7c03fe11f5a8504d4e4d625c314bc69b62f7620#diff-006da614e98d3640723944a9cf748c72320464e69620f7b3545ba847ffe8222aL40)

2024-12-26 04:47 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/handlers/admin/handle_transfer_admin.fc
> +
[removed](https://github.com/blubbofi/blubbo-contracts/commit/e7c03fe11f5a8504d4e4d625c314bc69b62f7620#diff-3a097b41fb1dd3541cd1355db8cc5b2064eda8d1d8ad1d5e603da1270f428e17L21)

2024-12-26 04:51 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/handlers/admin/handle_transfer_admin.fc
> +
e7c03fe11f5a8504d4e4d625c314bc69b62f7620 removed!

2024-12-26 05:03 UTC, Juyeong-Byeon commented on tests/SingleOwnerTonWallet.spec.ts
> +            success: true,
00ea395a57065db9dd793cb97d91a21a034eda4a

2024-12-26 05:03 UTC, Juyeong-Byeon commented on tests/SingleOwnerTonWallet.spec.ts
> +            success: true,
00ea395a57065db9dd793cb97d91a21a034eda4a

2024-12-26 05:03 UTC, Juyeong-Byeon commented on tests/SingleOwnerTonWallet.spec.ts
> +            success: false,
00ea395a57065db9dd793cb97d91a21a034eda4a

2024-12-26 05:38 UTC, Juyeong-Byeon commented on tests/SingleOwnerTonWallet.spec.ts
>          const approxOtherFeesLowerBound = toNano('0.0008');
I'm not sure about it.
Storage fee is Increased cus I added some of data to register and some lines of code which can increase storage fee based on [this docs](https://docs.ton.org/v3/documentation/smart-contracts/transaction-fees/fees-low-level#storage-fee:~:text=bits_count%E2%80%94count%20of%20bits%20used%20by%20smart%20contract).
But I'm not sure we should adjust lower bound.

2024-12-26 05:38 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/sotw_message_sender.fc
> +() message_sender::refund_excess(
c4541ac935a6bcbaa61da6638f60bacfa6507624 

```fc
;; WARNING: If raw_reserve is not called appropriately before using this function, 
;; the contract may unintentionally SEND ALL TON IT OWNS to the refund_address. (because of msg_mode::CARRY_ALL_BALANCE)
;; Ensure that raw_reserve is used to reserve the necessary funds before any operation
```

2024-12-26 05:38 UTC, Juyeong-Byeon commented on tests/SingleOwnerTonWallet.spec.ts
> +        });
51ff5749a3d9222951a52eef3c2e75a6a9ad2243 I split it to another case.

2024-12-26 05:39 UTC, Juyeong-Byeon commented on tests/SingleOwnerTonWallet.spec.ts
> +    it(`can transfer admin`, async () => {
Non-admin cannot transfer admin: [51ff574](https://github.com/blubbofi/blubbo-contracts/pull/57/commits/51ff5749a3d9222951a52eef3c2e75a6a9ad2243) 

Non-admin cannot upgrade code: I will work on it

2024-12-26 06:30 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/single_owner_ton_wallet.fc
> +}
63ca372fc763b269bc0db2365e7cb97269d2dadb removed fetch_admin_address function

2024-12-26 08:06 UTC, Juyeong-Byeon commented on tests/SingleOwnerTonWallet.spec.ts
> +    it(`can transfer admin`, async () => {
Non-admin cannot upgrade code: 6854f7d790a0514a88b6c8689b570445a19172d4

done!

2024-12-26 08:50 UTC, Juyeong-Byeon commented on contracts/single_owner_ton_wallet/sotw_message_sender.fc
> +() message_sender::refund_excess(
6a2df48a2f132ef770eb42ce3e80d51166501c24

I changed name of this function and removed from handlers (transfer admin, upgrade code).
I will implement refund logic again properly.

2024-12-27 05:12 UTC, 9oelM commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +async function createSingleOwnerTonWalletUpgradeTestContractCode(version: bigint, dumbOutput?: number) {
Move to TestUtils or Setup

2024-12-27 05:20 UTC, 9oelM commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +    it(`should refund excess toncoin on transfer admin is success`, async () => {
```suggestion
    it(`should refund excess toncoin on transfer admin`, async () => {
```

2024-12-27 05:22 UTC, 9oelM commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +        );
```suggestion
        const refundTx = flattenTransaction(
            findTransactionRequired(sendTransferAdminResult.transactions, {
                from: singleOwnerTonWallet.address,
                to: admin.address,
                success: true,
                op: Number(SingleOwnerTonWalletOpcode.excesses),
            }),
        );
```

findTransactionRequired will throw if tx not found already

2024-12-27 05:22 UTC, 9oelM commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +        const anotherAdmin = await blockchain.treasury('anotherAdmin');
```suggestion
        const notAdmin = await blockchain.treasury('anotherAdmin');
```

2024-12-27 05:23 UTC, 9oelM commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +        );
same

2024-12-27 05:43 UTC, 9oelM commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +    it(`should refund excess toncoin on upgrade is success`, async () => {
```suggestion
    it(`should refund excess toncoin on upgrade success`, async () => {
```

2024-12-27 05:48 UTC, Juyeong-Byeon commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +    it(`should refund excess toncoin on upgrade is success`, async () => {
09118253e72afc03c77ee70777f2d04ee63d8c63

2024-12-27 05:49 UTC, Juyeong-Byeon commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +        );
60a8b84c14daaa56bc610fdc432dbe8813d3cda6

2024-12-27 05:49 UTC, Juyeong-Byeon commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +        );
60a8b84c14daaa56bc610fdc432dbe8813d3cda6

2024-12-27 05:49 UTC, Juyeong-Byeon commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +        const anotherAdmin = await blockchain.treasury('anotherAdmin');
bf308947c4d10ead99e06d9f703128f175ae836c

2024-12-27 05:53 UTC, 9oelM commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +        BASE_RELATIVE__PATH,
```suggestion
        '..', '..',
```
I am not sure if the current code will run on Windows (if anyone in the future wants to run tests on Windows)

2024-12-27 05:57 UTC, Juyeong-Byeon commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +        BASE_RELATIVE__PATH,
commit 6d5a0edcfac2bacb3f6906566c2310b0b899d169

2024-12-27 05:57 UTC, Juyeong-Byeon commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +async function createSingleOwnerTonWalletUpgradeTestContractCode(version: bigint, dumbOutput?: number) {
4e0cb076f61ba9ed0e8071b9f48a76a3758955fa

2024-12-27 05:58 UTC, Juyeong-Byeon commented on tests/batch_2/SingleOwnerTonWallet.admin.spec.ts
> +    it(`should refund excess toncoin on transfer admin is success`, async () => {
16e8cdeee4eb65d22ee526e2043b587d067b6831

2024-12-27 06:03 UTC, 9oelM approved these changes

2024-12-27 06:05 UTC, merged