feat: implement top up ton
blubbofi/blubbo-contracts pull request #88
Opened 2024-12-28 09:23 UTC by Juyeong-Byeon

2024-12-28 13:23 UTC, 9oelM requested changes

2024-12-28 13:23 UTC, 9oelM commented on contracts/blubbo_user/blubbo_user.fc
> +      msg_value > fee::blubbo_user::MINIMUM_TOP_UP_TON
부등호 방햘 반대

2024-12-28 13:24 UTC, 9oelM requested changes

2024-12-28 13:24 UTC, 9oelM commented on contracts/op.fc
> +const int op::top_up_ton = 1011;
어드민 기능이 여기에 몰려있으니까 1200대로 해야할듯

2024-12-28 13:24 UTC, 9oelM commented on contracts/op.fc
> +const int op::top_up_ton = 1011;
1230 정도로

2024-12-28 13:32 UTC, Juyeong-Byeon commented on contracts/op.fc
> +const int op::top_up_ton = 1011;
c6a71d0c113cea0f1521ab21ec2b31bc36b894ac 수정완료!

2024-12-28 13:32 UTC, Juyeong-Byeon commented on contracts/blubbo_user/blubbo_user.fc
> +      msg_value > fee::blubbo_user::MINIMUM_TOP_UP_TON
good 감사합니다 7b1b18866718e9f07980a4fb47f38c56dc529f9e

2024-12-28 13:45 UTC, 9oelM commented on contracts/blubbo_user/blubbo_user.fc
> +  }
```suggestion
  if (op == op::top_up_ton) {
    throw_arg_if(
      sender_address,
      errors::INSUFFICIENT_BLUBBO_USER_TOP_UP_TON_AMOUNT, 
      msg_value < fee::blubbo_user::MINIMUM_TOP_UP_TON
    );
 return ();
  }
```

이러케하고 95번째줄에 옮기는게 나을듯

2024-12-28 13:45 UTC, 9oelM commented on contracts/blubbo_user/blubbo_user.fc
> +    | op == op::top_up_ton
이거는지우고 (for the best clarity)

2024-12-28 13:50 UTC, Juyeong-Byeon commented on contracts/blubbo_user/blubbo_user.fc
> +  }
good 이방향도 고민 했었는데 헨들러 모여있는것도 좋은 방향 같아서 이렇게 처리하긴 했었음

2024-12-28 13:52 UTC, Juyeong-Byeon commented on contracts/blubbo_user/blubbo_user.fc
> +    | op == op::top_up_ton
0b29aa98fcdaf890804c42c3e3e7e34afd73c1d6

2024-12-28 13:52 UTC, Juyeong-Byeon commented on contracts/blubbo_user/blubbo_user.fc
> +  }
0b29aa98fcdaf890804c42c3e3e7e34afd73c1d6

2024-12-28 13:58 UTC, 9oelM requested changes

2024-12-28 13:58 UTC, 9oelM commented on contracts/blubbo_user/blubbo_user.fc
> +      sender_address,
```suggestion
      msg_value,
```

2024-12-28 23:00 UTC, Juyeong-Byeon commented on contracts/blubbo_user/blubbo_user.fc
> +      sender_address,
[7702931](https://github.com/blubbofi/blubbo-contracts/pull/88/commits/7702931bc59c5872740513c093b7f0b1df625e8d)

2024-12-29 02:03 UTC, 9oelM commented on tests/batch_3/BlubboUser.spec.ts
> +        const balanceAfterTopUp = contract.balance;
contract.balance가 아무것도 안했는데 그냥 바뀜??? 아닐거같은데..

2024-12-29 02:03 UTC, 9oelM commented on tests/batch_3/BlubboUser.spec.ts
> +        const balanceAfterTopUp = contract.balance;
여기서 getContract 한번 더해야하지 않을까

2024-12-29 04:03 UTC, Juyeong-Byeon commented on tests/batch_3/BlubboUser.spec.ts
> +        const balanceAfterTopUp = contract.balance;
이거 애매해서 테스트 해봤는데, 바뀌더라고

[getContract](https://github.com/blubbofi/sandbox/blob/main/src/blockchain/BlockchainStorage.ts#L18) 하면 저장한 contract object 레퍼런스 유지하면서 그대로 반환하고 내부적으로 레퍼런스 유지돼서 그런듯 [assert도](https://github.com/blubbofi/blubbo-contracts/pull/88/files#diff-6c8202211e204ee9a8a7f92f08eaa9329b9b66cae4de2aad926758e644fa2025R63) 추가해둠

2024-12-29 04:19 UTC, Juyeong-Byeon commented on tests/batch_3/BlubboUser.spec.ts
> +        const balanceAfterTopUp = contract.balance;
sandBox 코드좀 더 살펴봤는데, 

값 변경하기 위해서 [message send 하면](https://github.com/blubbofi/sandbox/blob/main/src/blockchain/BlockchainSender.ts#L15) 공유되고있는 blockchin 객체에 pushMessage 하고 내부적으로 message 처리하는 과정인 [processQueue](https://github.com/blubbofi/sandbox/blob/main/src/blockchain/Blockchain.ts#L467) 돌고 [processinternel](https://github.com/blubbofi/sandbox/blob/main/src/blockchain/Blockchain.ts#L399) 호출하는데, 거기서도 getContract 이용하는데 거기서 윗 댓글에 남긴 storeage에 저장된 contract를 가져오는 [getContract](https://github.com/blubbofi/sandbox/blob/main/src/blockchain/Blockchain.ts#L643)를 호출함

2024-12-30 02:47 UTC, 9oelM approved these changes

2024-12-30 02:53 UTC, merged